version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Skipping integration tests
      - mvn clean install -PskipPostgresTests
artifacts:
  files:
    - target/*.jar
